### ISSUE TITLE
Create a showcase of websites using the Standards

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#469]
We have a list of over [100 websites using the Standards](https://github.com/18F/web-design-standards/blob/develop/WHO_IS_USING_USWDS.md), but it would help people see the impact, scope, and scale if they could see **visual examples of these websites**. It could also help them envision the types of customization that can be done to the Standards.

## Design
Something like the design of [18F's feature project page](https://18f.gsa.gov/what-we-deliver/) is something we could employ (i.e. a grid of projects). Could be vertically shorter.
<img width="570" alt="screen shot 2017-12-21 at 12 17 09 pm" src="https://user-images.githubusercontent.com/5249443/34273967-791c55f4-e64b-11e7-838e-acf598ef094f.png">

## MVP functionality
A screenshot of the site and title linking to the project (optional short description). See http://styleguides.io/examples

## 2.0 functionality
Write content for each project and link to a page with a write up. We can also plugin a section of featured sites on the homepage.

## TODO

- [ ] Choose 10-20 representative websites to feature
- [ ] Design a page for these examples
- [ ] Gather screenshots and optimize file size
- [ ] Create a jekyll collection or data file which will generate the items on the page  

Related #211, this was previously designed as a [vertically stacked showcase](https://gsa.invisionapp.com/share/35BB46989#/screens/228975811), but a grid may make better use of space.
![gsa invisionapp com_share_35bb46989](https://user-images.githubusercontent.com/5249443/34274092-f59d9a70-e64b-11e7-80e6-b45fad7afb24.png)

A similar design was also used on the launch of the project:
![homepage examples copy](https://user-images.githubusercontent.com/5249443/34274251-9c28a952-e64c-11e7-8af6-0d76a2f0711c.png)

### Related example
See filter used on https://oes.gsa.gov/work/

**Comment by maya** [comment]
## Potential sites to feature

Would like to feature 10-20 mature, well-designed implementations, diverse customizations, high-impact projects, and recognizable agencies.

- vets.gov
- USA.gov
- vote.gov
- epa.gov
- Plainlanguage.gov
- Pubmed journals (NCBI)
- USDA New Farmers
- ACCESS NYC

_Feel free to edit..._

**Comment by line47** [comment]
NSF SBIR - https://seedfund.nsf.gov/
