### ISSUE TITLE
[Repo] Remove assets folder from the repo, only have it created by the build process

### ISSUE THREAD

**Issue by yozlet** [18F/web-design-standards-docs#8]
## Description

Everything in the `assets/` folder should be there as a result of the build process, not because it's been committed there. All assets that belong to the docs (as opposed to those from a vendor/module, including the `uswds` package) should start in a separate folder (e.g. `src/`).

- [x] Remove images
  - [x] Remove all USWDS package images (unfortunately, they're mixed in with the docs images) (#9)
  - [x] Move all docs images to `src/images/`, have build step copy them in (#10)
  - [ ] ~~Ideally, images copied from `uswds` should go to `assets/img/vendor/uswds/` (but this will require lots of doc changes - probably automatable. We may want to postpone this work to a later date.)~~ (Postponed, no longer part of this issue, but still in consideration at #11)
- [x] Remove styles
  - [x] Make sass build step copy `prism.css` from `node_modules/` (#12)
  - [x] Move all docs SCSS to `src/scss/`, have build step copy them in (#13)
- [x] Remove Javascript
  - [x] Make JS build step copy vendor JS from `node_modules/` (#14)
  - [x] Move all docs JS to `src/js/`, have build step target `assets/js/` for `styleguide.js` output (#15)
- [x] Remove `assets/` (#16)

**Comment by rogeruiz** [comment]
This shouldn't be entirely necessary anymore @yozlet. PrismJS has been removed since it is now longer needed to generate `<markup>` code on the client. It gets built in `config/gulp/html.js` now.

**Comment by yozlet** [comment]
@rogeruiz Interesting, somehow `config/gulp/html.js` didn't make it over to this new repo. `website.js` also seems to be missing, yet the site builds OK. (I probably don't fully understand what `website.js` is for.) Should I just copy them over? @juliaelman?

**Comment by juliaelman** [comment]
@yozlet good questions and I have some answers! 🎉  Going to write this up here as a reference point on how the gulp tasks have been updated/changed from the original repo to this one.

`html.js` needs to be added in and will [be part of this work](https://github.com/18F/web-design-standards-docs/issues/6). These tasks are not in this repo b/c the addition of that `gulp` task was added *after* the initial implementation of this repo. Check out [this PR](https://github.com/18F/web-design-standards/pull/1370) for that implementation.

As for the [`website.js`](https://github.com/18F/web-design-standards/blob/staging/config/gulp/website.js) file, after evaluating it seemed that the tasks could be simplified. The tasks included cleaning out and copying assets, running `jekyll build`, building the website, running bundler and serving the website. Since the `build` task in the main repo refers to the building of the Standards package, it made sense to utilize that file for the website build tasks  instead and remove the `website.js` file entirely. Also, the `jekyll` commands are run via the `npm` scripts, rather than inside of the `gulp` tasks themselves.

Hope that makes sense and am happy to go over my thinking and the re-architecture over chat too!

**Comment by juliaelman** [comment]
It looks like the last bit is to have all of the `uswds` assets pipe into a `vendor` folder inside of their "type" folder (e.g. css/vendor).

@yozlet if you are okay with this, and since we are in the last day of the sprint, would you be 👌 if we added a few more issues similar to this one? https://github.com/18F/web-design-standards-docs/issues/11 Not sure it's something we will want to focus on for Sprint 5, but it would be good to have them prepared just in case 😄

**Comment by yozlet** [comment]
@juliaelman Ack, sorry, missed this question at the time! If there's still similar stuff to do, let's talk.

The one remaining issue here is #11, and that's less urgent, so I've struck it from the tasklist and calling everything else DONE.
